### ISSUE TITLE
[FEAT] Make cuda available

### ISSUE THREAD

**Issue by mricharz** [linuxserver/docker-piper#4]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would like to have the ability to activate cuda as it is supported by piper itself.
The piper documentation says we need to install `onnxruntime-gpu` and add `--cuda` on the start script.

### Reason for change

Piper should work much faster with cuda support on nvidia cards.

### Proposed code change

1. Install `onnxruntime-gpu` in docker container.
2. Add a variable to docker image with will be passed to the start script like `EXTRA_PARAMS`
With such a variable the user could add additional parameters to the piper start script as they like.

**Comment by mricharz** [comment]
> ```yaml
>     environment:
>       - NVIDIA_VISIBLE_DEVICES=all
>     runtime: nvidia # https://docs.linuxserver.io/images/docker-plex/#nvidia
> ```
> 
> Append `--cuda` cmd there https://github.com/linuxserver/docker-piper/blob/main/root/etc/s6-overlay/s6-rc.d/svc-piper/run#L7-L16 ?

Yes. Should be the correct place.

**Comment by mricharz** [comment]
You can find the documentation [here](https://github.com/rhasspy/piper?tab=readme-ov-file#running-in-python)

>If you'd like to use a GPU, install the `onnxruntime-gpu` package:
>
>
>``` sh
>.venv/bin/pip3 install onnxruntime-gpu
>```
>
>and then run `piper` with the `--cuda` argument. You will need to >have a functioning CUDA environment, such as what's available in [NVIDIA's PyTorch containers](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch).

**Comment by srvoets** [comment]
> You can find the documentation [here](https://github.com/rhasspy/piper?tab=readme-ov-file#running-in-python)
> 
> > If you'd like to use a GPU, install the `onnxruntime-gpu` package:
> > ```shell
> > .venv/bin/pip3 install onnxruntime-gpu
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then run `piper` with the `--cuda` argument. You will need to have a functioning CUDA environment, such as what's available in [NVIDIA's PyTorch containers](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch).

yes you can do that in the console, but it needs to survive updates etc.  

I found this due to the same issue.

**Comment by fawzib** [comment]
is this still in progress?

**Comment by mricharz** [comment]
Some linuxserver docker images have mods. Maybe you can create a mod for the `onnxruntime-gpu`. I don't know how the mods for linuxserver containers work.

Or you could create a separate docker file with GPU support with `onnxruntime-gpu` installed.

I hope we can find a solution for the GPU support. ☺️

**Comment by aptalca** [comment]
#8

**Comment by roryeckel** [comment]
I made a comment (maybe in the wrong place): https://github.com/linuxserver/docker-piper/pull/8#issuecomment-2572020455

I appreciate the work on this project very much. But it seems like cuda is not working with these changes
